version: "3.8"

services:
  server:
    image: "${NCP_CONTAINER_REGISTRY}/core:${GITHUB_SHA}"
    container_name: core
    volumes:
      - /root/application.yml:/config/application.yml:ro
      - /root/application-main.yml:/config/application-main.yml:ro
    environment:
      TZ: Asia/Seoul
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/config/"
      SPRING_PROFILES_ACTIVE: "main"
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - core-network
  redis:
    image: redis:6.0.9
    container_name: core-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - core-network

volumes:
  redis-data:

networks:
  core-network:
    driver: bridge